In [2]:
import pandas as pd

In [3]:
perfume_men= pd.read_csv(".//ebay_mens_perfume.csv")

In [4]:
perfume_men

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [5]:
perfume_men.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               997 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          889 non-null    float64
 6   availableText      997 non-null    object
 7   sold               994 non-null    float64
 8   lastUpdated        947 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.3+ KB

In [6]:
perfume_men.groupby('brand')['price'].sum()

brand
2nd To None              6.65
AS PHOTOS               34.68
AS PICTURE SHOWN       125.99
AS SHOW                530.43
AS SHOWN               385.94
                        ...
king of kings           79.99
rue21                   25.00
united scents           14.99
ysl                     38.00
~ DOLCE & GABBANA ~     54.99
Name: price, Length: 246, dtype: float64

In [8]:
brand_price = perfume_men.groupby(['brand','title'])['price'].sum()

In [9]:
brand_price

brand                title
2nd To None          6 For $19.95 MEN(M) WOMEN(W) & UNISEX(U) Body Oil Fragrances 10 ml Roll On Pure       6.65
AS PHOTOS            New Carolina-Herrera 212 NYC Men Eau De Toilette 3.4 oz/ 100 ml                      34.68
AS PICTURE SHOWN     Silver Mountain Water Eau De Parfum 3.3 / 3.4 OZ 100 ML Spray For men New In Box    125.99
AS SHOW              A-v-entus Eau de Parfum 3.3 oz 100ML Millesime EDP Col-ogne for Men New In Box      109.99
                     A-ventu-s for Men 3.3 OZ./ 100 ML.Eau de Parfum Spray for Men New Sealed Box         99.49
                                                                                                          ...
king of kings        King of Kings Royal Blue Parfum 3.4 oz for Men is a wonderful men's fragrance        79.99
rue21                Rue 21 CJ Black Cologne Spray  1.7 fl. Oz  New Without Box                           25.00
united scents        Men's  Perfume Black Intense 3.4 Fl Oz Parfum Fragrance                              14.99
ysl                  YSL Yves Saint Laurent Y Eau de Toilette Spray 3.3 oz/100ML EDT Mens Cologne New     38.00
~ DOLCE & GABBANA ~  DOLCE & GABBANA ~ THE ONE EAU DE PARFUM SPRAY For Men 3.3 OZ 100 Ml White Box        54.99
Name: price, Length: 971, dtype: float64

In [14]:
most_cost_brand = perfume_men.groupby(['brand'])['price'].sum().sort_values(ascending=False)

In [15]:
most_cost_brand

brand
Giorgio Armani           3414.36
Paco Rabanne             2634.99
Yves Saint Laurent       2072.73
Dolce&Gabbana            1930.18
Ralph Lauren             1550.82
                          ...
Coty Inc.                   9.21
Al Rehab                    8.99
Dvyne Fragrances            8.00
2nd To None                 6.65
Alexandria Fragrances       3.00
Name: price, Length: 246, dtype: float64

In [27]:
perfume_men ['title'].value_counts()

title
YSL Yves Saint Laurent Y Eau de Perfume Spray Cologne For Men 3.3 oz 100ML          4
Hawas for him Eau De Parfum By Rasasi 100ml 3.4 FL OZ NEW                           4
SEALED NEW CUPID 2.0 HYPNOSIS MENâ€™S PHEROMONE COLOGNE 1.7 OZ MEET MORE HOT WOMEN    3
New 2024 Sexy Cologne Cupid Hypnosis Long Lasting Pheromone Perfume for Men         3
1/2PCS 50ml Men's Pheromone-Cupid Infused Perfume- Hypnosis Cologne Fragrances      3
                                                                                   ..
PS by Paul Sebastian Cologne for Men 8 / 8.0 oz Brand New In Box                    1
Ralph Lauren Polo Black 4.2 oz / 125 ml Eau De Toilette Spray For Men Brand New!    1
HALLOWEEN MAN J. Del Pozo cologne edt 4.2 oz NEW IN BOX                             1
SpiceBomb Extreme Made Stronger With Pheromones For Super Hot Sexual Attraction!    1
Beyond Paradise by Estee Lauder for Men Cologne Spray EDT 0.5 oz , New              1
Name: count, Length: 966, dtype: int64

In [22]:
perfume_men[ perfume_men['title'] == 'YSL Yves Saint Laurent Y Eau de Perfume Spray Cologne For Men 3.3 oz 100ML' ]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
104,As Shown,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Eau de Parfum,49.99,US $49.99,5.0,5 available / 45 sold,45.0,"May 24, 2024 00:15:22 PDT","Ottawa,California, Canada"
210,Unbranded,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Y,49.99,US $49.99/ea,8.0,8 available / 68 sold,68.0,"May 19, 2024 18:38:36 PDT","New Jersey, United States"
223,fragrance,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Eau de Parfum,46.99,US $46.99,2.0,2 available / 3 sold,3.0,"May 24, 2024 00:24:54 PDT","New City, New York, United States"
448,As Show,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Eau de Parfum,39.99,US $39.99/ea,8.0,8 available / 10 sold,10.0,"May 19, 2024 18:09:04 PDT","Dayton,New Jersey, Hong Kong"

In [23]:
top_brand = perfume_men.groupby('brand')['sold'].sum().sort_values(ascending=False)[0:10]

In [32]:
top_brand

brand
Calvin Klein     97572.0
Versace          96519.0
Davidoff         54944.0
Azzaro           38305.0
Armaf            24282.0
Kenneth Cole     23716.0
Paco Rabanne     21579.0
Liz Claiborne    21341.0
Burberry         19286.0
2nd To None      18882.0
Name: sold, dtype: float64

In [33]:
perfume_men.groupby(['brand','title'])['available'].sum().sort_values(ascending=False)

brand              title
Calvin Klein       ETERNITY for Men by CALVIN KLEIN 3.3 / 3.4 oz EDT New In box                      842.0
Polo Ralph Lauren  POLO SPORT Ralph Lauren 4.2 oz Cologne for Men EDT New in Box                     756.0
Guy Laroche        DRAKKAR NOIR by Guy Laroche 3.4 oz / 3.3 oz edt spray for Men New UNBOXED         620.0
Coach              COACH NEW YORK by Coach cologne for men EDT 3.3 / 3.4 oz New In Box               487.0
Ralph Lauren       POLO by Ralph Lauren 4.0 oz Cologne EDT Men GREEN New in Box                      484.0
                                                                                                     ...
Paco Rabanne       Phantom by Paco Rabanne 5.1 oz EDT Refillable Cologne for Men Brand New In Box      0.0
Calvin Klein       Obsession Night by CK Calvin Klein 4.0 oz EDT Cologne for Men New In Box            0.0
Parfums de Marly   Parfums de Marly Kalan 4.2 fl oz / 125 ml Spray with box Men's Fragrances           0.0
                   Parfums de Marly LAYTON Royal Essence EDP Spray 4.2 fl oz. NEW Sealed Box           0.0
Karl Lagerfeld     Lagerfeld Classic by Lagerfeld 5 oz EDT Cologne for Men New In Box                  0.0
Name: available, Length: 971, dtype: float64

In [16]:
perfume_men.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               997 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          889 non-null    float64
 6   availableText      997 non-null    object
 7   sold               994 non-null    float64
 8   lastUpdated        947 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.3+ KB

In [20]:
perfume_men.isna().value_counts

<bound method DataFrame.value_counts of      brand  title   type  price  priceWithCurrency  available  availableText  \
0    False  False  False  False              False      False          False
1    False  False  False  False              False      False          False
2    False  False  False  False              False      False          False
3    False  False  False  False              False      False          False
4    False  False  False  False              False       True          False
..     ...    ...    ...    ...                ...        ...            ...
995  False  False  False  False              False      False          False
996  False  False  False  False              False      False          False
997  False  False  False  False              False      False          False
998  False  False  False  False              False      False          False
999  False  False  False  False              False      False          False

      sold  lastUpdated  itemLocation
0    False        False         False
1    False        False         False
2    False        False         False
3    False        False         False
4    False        False         False
..     ...          ...           ...
995  False        False         False
996  False        False         False
997  False        False         False
998  False        False         False
999  False        False         False

[1000 rows x 10 columns]>

In [27]:
perfume_men[perfume_men['available'].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
7,Unbranded,Parfums De-Marly-Haltane Eau de Parfum spray 4...,Eau de Parfum,85.00,US $85.00,NaN,Last One / 6 sold,6.0,"May 24, 2024 00:10:39 PDT","Ithaca, New York, United States"
20,Dolce & Gabbana,Light Blue by Dolce & Gabbana 4.2 oz Cologne f...,Eau de Toilette,29.94,US $29.94/ea,NaN,"Limited quantity available / 9,208 sold",9208.0,"May 23, 2024 20:04:11 PDT","Hackensack, New Jersey, United States"
29,Penhaligon's,Penhaligon's The Tragedy of Lord George 2.5oz ...,Eau de Parfum,99.99,US $99.99,NaN,Last One / 30 sold,30.0,"May 20, 2024 04:16:27 PDT","Brenham, Texas, United States"
36,Rasasi,Rasasi Men's Hawas EDP Spray 3.4 oz Fragrances...,Eau de Parfum,45.11,US $45.11,NaN,Limited quantity available / 258 sold,258.0,"May 24, 2024 09:50:28 PDT","Brooklyn, New York, United States"
...,...,...,...,...,...,...,...,...,...,...
920,Elizabeth Taylor,Elizabeth Taylor PASSION Cologne Spray for Men...,Eau de Cologne,17.17,US $17.17,NaN,Last One / 4 sold,4.0,"May 24, 2024 07:15:49 PDT","Ontario, California, United States"
922,Gucci,Gucci Guilty Black 3.0 oz EDT Cologne for Men ...,Eau de Toilette,68.30,US $68.30,NaN,Limited quantity available / 137 sold,137.0,"May 24, 2024 07:59:03 PDT","Hackensack, New Jersey, United States"
925,Bath & Body Works,Bath & Body Works Men's Collection Fragrance C...,Body Spray,10.91,US $10.91,NaN,Last One / 654 sold,654.0,"May 16, 2024 00:14:43 PDT","Modesto, California, United States"
934,Cologne,New 10x New Random Unique Men's Fragrance Colo...,Perfume,19.90,US $19.90,NaN,More than 10 lots available (10 items per lot)...,331.0,"Nov 21, 2023 08:32:55 PST","Stony Brook, New York, United States"
988,Michael Jordan,Michael Jordan by Michael Jordan 3.4 oz Cologn...,Eau de Cologne,20.48,US $20.48/ea,NaN,"Limited quantity available / 2,624 sold",2624.0,"May 22, 2024 21:41:09 PDT","Hackensack, New Jersey, United States"

In [32]:
perfume_men[perfume_men['type'].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
81,Calvin Klein,Ck One by Calvin Klein Cologne Perfume Unisex ...,NaN,23.89,US $23.89/ea,NaN,"Limited quantity available / 54,052 sold",54052.0,"May 24, 2024 03:59:39 PDT","Hackensack, New Jersey, United States"
138,AS SHOW,Bleu De Eau de parfum EDP 100ml 3.4 oz Cologne...,NaN,89.99,US $89.99,5.0,5 available / 5 sold,5.0,"May 14, 2024 20:43:05 PDT","New York,United States, Hong Kong"
606,Milestone Perfumes,Intimation By Milestone Eau de Parfum 3.4 oz Men,NaN,19.89,US $19.89,10.0,More than 10 available / 21 sold,21.0,"May 24, 2024 10:13:17 PDT","Miami, Florida, United States"

In [29]:
perfume_men[perfume_men.isnull().any(axis=1)]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
7,Unbranded,Parfums De-Marly-Haltane Eau de Parfum spray 4...,Eau de Parfum,85.00,US $85.00,NaN,Last One / 6 sold,6.0,"May 24, 2024 00:10:39 PDT","Ithaca, New York, United States"
20,Dolce & Gabbana,Light Blue by Dolce & Gabbana 4.2 oz Cologne f...,Eau de Toilette,29.94,US $29.94/ea,NaN,"Limited quantity available / 9,208 sold",9208.0,"May 23, 2024 20:04:11 PDT","Hackensack, New Jersey, United States"
27,Azzaro,Azzaro The Most Wanted 3.38 oz./100 ml. PARFUM...,Eau de Parfum,87.99,US $87.99,2.0,2 available / 4 sold,4.0,NaN,"NEW YORK, United States"
29,Penhaligon's,Penhaligon's The Tragedy of Lord George 2.5oz ...,Eau de Parfum,99.99,US $99.99,NaN,Last One / 30 sold,30.0,"May 20, 2024 04:16:27 PDT","Brenham, Texas, United States"
...,...,...,...,...,...,...,...,...,...,...
934,Cologne,New 10x New Random Unique Men's Fragrance Colo...,Perfume,19.90,US $19.90,NaN,More than 10 lots available (10 items per lot)...,331.0,"Nov 21, 2023 08:32:55 PST","Stony Brook, New York, United States"
945,Giorgio Armani,Lot of 12 - Acqua Di Gio Profondo - Men's Luxu...,Eau de Parfum,24.00,US $24.00,3.0,3 available / 2 sold,2.0,NaN,"Arlington Heights, Illinois, United States"
948,Parfums de Marly,PDM PARFUMS DE MARLY LAYTON EXCLUSIF 1.5ml .05...,Parfum,12.00,US $12.00,10.0,More than 10 available / 19 sold,19.0,NaN,"Albany, New York, United States"
988,Michael Jordan,Michael Jordan by Michael Jordan 3.4 oz Cologn...,Eau de Cologne,20.48,US $20.48/ea,NaN,"Limited quantity available / 2,624 sold",2624.0,"May 22, 2024 21:41:09 PDT","Hackensack, New Jersey, United States"
994,Dolce&Gabbana,Dolce & Gabbana Cologne For Men Eau De Toilett...,Eau de Toilette,27.99,US $27.99/ea,7.0,7 available / 24 sold,24.0,NaN,"Des Moines, Iowa, United States"

In [45]:
perfume_men = perfume_men.copy()

In [46]:
perfume_men.dropna(axis=0, inplace=True)

In [47]:
perfume_men

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
5,Multiple Brands,Men's Perfume Sampler 10pcs Sample Vials Desig...,Perfume,14.99,US $14.99,10.0,More than 10 available / 79 sold,79.0,"May 23, 2024 06:57:41 PDT","Houston, Texas, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [48]:
perfume_men.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              842 non-null    object
 1   title              842 non-null    object
 2   type               842 non-null    object
 3   price              842 non-null    float64
 4   priceWithCurrency  842 non-null    object
 5   available          842 non-null    float64
 6   availableText      842 non-null    object
 7   sold               842 non-null    float64
 8   lastUpdated        842 non-null    object
 9   itemLocation       842 non-null    object
dtypes: float64(3), object(7)
memory usage: 72.4+ KB

In [50]:
perfume_men.dropna(axis=0, inplace=True)

In [51]:
perfume_men

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
5,Multiple Brands,Men's Perfume Sampler 10pcs Sample Vials Desig...,Perfume,14.99,US $14.99,10.0,More than 10 available / 79 sold,79.0,"May 23, 2024 06:57:41 PDT","Houston, Texas, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [34]:
fill = perfume_men.copy()

In [35]:
fill

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [36]:
fill['available'].fillna(0)

0      10.0
1       8.0
2      10.0
3       2.0
4       0.0
       ...
995    45.0
996    10.0
997     2.0
998     2.0
999    10.0
Name: available, Length: 1000, dtype: float64

In [38]:
fill['available'].fillna(fill['available'].min())## mean,sum,median,max,std can replace the min()

0      10.0
1       8.0
2      10.0
3       2.0
4       2.0
       ...
995    45.0
996    10.0
997     2.0
998     2.0
999    10.0
Name: available, Length: 1000, dtype: float64

In [39]:
fill['available'].ffill()

0      10.0
1       8.0
2      10.0
3       2.0
4       2.0
       ...
995    45.0
996    10.0
997     2.0
998     2.0
999    10.0
Name: available, Length: 1000, dtype: float64

In [40]:
fill['available'].bfill()

0      10.0
1       8.0
2      10.0
3       2.0
4      10.0
       ...
995    45.0
996    10.0
997     2.0
998     2.0
999    10.0
Name: available, Length: 1000, dtype: float64

In [41]:
fill['available'].ffill(inplace=True)

In [44]:
fill['available']

0      10.0
1       8.0
2      10.0
3       2.0
4       2.0
       ...
995    45.0
996    10.0
997     2.0
998     2.0
999    10.0
Name: available, Length: 1000, dtype: float64

In [45]:
fill['type'].fillna('not specified', inplace= True)

In [46]:
fill['type']

0        Eau de Parfum
1        Eau de Parfum
2      Eau de Toilette
3      Eau de Toilette
4           Fragrances
            ...
995    Eau de Toilette
996    Eau de Toilette
997    Eau de Toilette
998    Eau de Toilette
999      Cologne spray
Name: type, Length: 1000, dtype: object

In [47]:
fill['type']

0        Eau de Parfum
1        Eau de Parfum
2      Eau de Toilette
3      Eau de Toilette
4           Fragrances
            ...
995    Eau de Toilette
996    Eau de Toilette
997    Eau de Toilette
998    Eau de Toilette
999      Cologne spray
Name: type, Length: 1000, dtype: object

In [48]:
fill['brand'].fillna('Unbranded',inplace = True)

In [49]:
fill['lastUpdated'].bfill(inplace= True)

In [50]:
fill['lastUpdated']

0      May 24, 2024 10:03:04 PDT
1      May 23, 2024 23:07:49 PDT
2      May 22, 2024 21:55:43 PDT
3      May 24, 2024 03:30:43 PDT
4      May 24, 2024 07:56:25 PDT
                 ...
995    May 24, 2024 08:14:07 PDT
996    May 23, 2024 08:39:30 PDT
997    May 23, 2024 15:27:18 PDT
998    May 20, 2024 13:20:54 PDT
999    Feb 28, 2024 07:27:01 PST
Name: lastUpdated, Length: 1000, dtype: object

In [68]:
fill['sold'].fillna('missing', inplace= True)

In [69]:
fill['sold']

0       116.0
1        48.0
2        27.0
3       159.0
5        79.0
        ...
995    1613.0
996      31.0
997     305.0
998      22.0
999      24.0
Name: sold, Length: 842, dtype: float64

In [72]:
fill['availableText'].fillna('not generated', inplace= True)

In [74]:
fill['availableText']

0      More than 10 available / 116 sold
1                  8 available / 48 sold
2       More than 10 available / 27 sold
3                 2 available / 159 sold
5       More than 10 available / 79 sold
                     ...
995            45 available / 1,613 sold
996     More than 10 available / 31 sold
997               2 available / 305 sold
998                2 available / 22 sold
999     More than 10 available / 24 sold
Name: availableText, Length: 842, dtype: object