In [1]:
import pandas as pd

In [2]:
crypto_df= pd.read_csv(".//Crypto.csv")

In [3]:
crypto_df

,name,abbr,Crypturl,Price,Volume24hrs,marketcap,Circulatingsupply,Maxsupply,Totalsupply,Date_taken
0,Bitcoin,BTC,https://crypto.com/price/bitcoin,6.273267e+04,272076.9766,"2,51,418.65",3.065439e+06,876052496.2,437497786.1,09/08/2007
1,Ethereum,ETH,https://crypto.com/price/ethereum,3.027220e+03,981408.7883,"5,02,924.62",2.326224e+06,444082823.2,705224728.4,13/12/2007
2,Tether,USDT,https://crypto.com/price/tether,9.999000e-01,944792.0394,"8,15,637.23",2.207000e+06,604510133.4,716566396.6,03/03/2004
3,BNB,BNB,https://crypto.com/price/bnb,5.938500e+02,556334.5330,"3,23,746.05",2.400147e+05,150451882.8,685308596.6,06/06/2001
4,Solana,SOL,https://crypto.com/price/solana,1.525900e+02,866929.0575,"8,05,143.57",2.957790e+06,284280494.2,647877254.0,06/08/2019
...,...,...,...,...,...,...,...,...,...,...
21342,ぺぺ,ぺぺ,https://crypto.com/price/pepe-eth,8.870000e-11,781384.1263,"3,11,061.69",2.962194e+06,552536338.4,305845288.5,01/09/2015
21343,喵喵喵喵喵,喵喵喵喵喵,https://crypto.com/price/miaomiaomiaoerc20,8.500000e-07,120877.9300,"7,33,230.16",3.026933e+06,930507777.8,287947911.6,05/02/2000
21344,四皇 - Four Emperors,YONKŌ,https://crypto.com/price/four-emperors,7.988930e+03,431924.5009,"81,533.88",1.397512e+06,476058576.1,392855467.6,08/12/2023
21345,忠 LOYAL,LOYAL 忠,https://crypto.com/price/loyal,1.875000e-05,238668.9598,"1,92,828.64",2.122169e+06,563586350.9,334356379.1,13/04/2019
21346,无条件为你,无条件为你,https://crypto.com/price/wtjwn,4.900000e-08,441316.8639,"2,61,747.39",3.108708e+05,805662706.9,512283391.5,04/07/2012

In [4]:
crypto_df.dtypes

name                  object
abbr                  object
Crypturl              object
Price                float64
Volume24hrs          float64
marketcap             object
Circulatingsupply    float64
Maxsupply            float64
Totalsupply          float64
Date_taken            object
dtype: object

In [5]:
crypto_df['Price'].max()

1595659480.0

In [7]:
crypto_df.describe()

,Price,Volume24hrs,Circulatingsupply,Maxsupply,Totalsupply
count,2.134700e+04,21347.000000,2.134700e+04,2.134700e+04,2.134700e+04
mean,7.524758e+04,488514.745820,2.109302e+06,5.000418e+08,5.005749e+08
std,1.092127e+07,283506.240054,1.225969e+06,2.876037e+08,2.893756e+08
min,0.000000e+00,103.983721,1.669758e+02,2.041145e+04,5.213366e+04
25%,1.000000e-05,241306.259550,1.041184e+06,2.518438e+08,2.498050e+08
50%,9.548000e-04,487505.451700,2.103832e+06,5.013132e+08,5.028731e+08
75%,3.687500e-02,733224.487850,3.163273e+06,7.469720e+08,7.507950e+08
max,1.595659e+09,981555.184500,4.251433e+06,9.989293e+08,9.999478e+08